var titre=new Array()
var breve=new Array()




titre[titre.length]="Vos contributions"
breve[breve.length]="Cette page acceuille des contributions et des informations sur l'actualité et les débats sur le pracarité sous ses différents angles de vues.<br>Envoyez vos propositions de contribution à precarite.fr@altercarto.com"

titre[titre.length]="Au delà des Chiffres du chômage,saisir la précarité"
breve[breve.length]="Si l’actualité politique et médiatique s’est focalisée pendant la campagne présidentielle, sur le compte du chômage, notamment avec le manège de l’Insee quant à la publication des réajustement annuels résultant de l’enquête emploi, le collectif <a href='http://acdc2007.free.fr/' target='_blank'>ACDC</a>, qui a conduit la bataille sur le chiffre n’en reste pas à la seule perspective de compter les chômeurs. La visée du collectif est plutôt de parvenir à un dispositif de statistique publique qui rende compte de la réalité de la précarité.<br>Dans cette perspective ils proposent non seulement de prendre en compte les chômeurs écartés des chiffres officiels, mais aussi de prende en compte l’emploi \"inadéquat\" (très bas salaire, travail pénible, temps partiel contraint, CDD,...)<br>Il s’agirait là certainement d’une avancée considérable.<br>Reste que, au delà des radiés abusivement, des allocataires des régimes de solidarité dispensés de recherche d’emploi, des préretraités à l’issue de plan sociaux, etc. une autre part des précaires doit encore faire sa place dans la bataille des chiffres : les handicapés. Non seulement une grande part d’entre eux sont demandeurs d’emploi ou cherchent les conditions décentes de réalisation d’un travail, mais une part des titulaires de l’AAH, allocation adultes handicapés l’est devenu à la suite de lésions dans le travail.<br>Plus généralement, le recours au reclassement de travailleurs prématurément \"usés\" ou vieillis dans la catégorie des bénéficiaires de l’AAH apparaît comme un procédé de plus en plus courant. L’exclusion qui en découle comporte de multiple aspects : outre le fait qu’ils sont mutilés dans leurs corps, et placés dans une situation de précarité financière (l’AAH est un mimum social), les gens concernés sont exclus du compte et par conséquent des politiques relatives aux travailleurs. Mais il a fallu aussi que l’usure au travail, la pénibilité etc.. et les pressions sociales et morales qui vont avec, soient assez fortes pour que les personnes aient accepté d’être ainsi reclassées, jusque parfois avoir intériorisé \"l’état de handicap\" comme une réalité qui les mets \"à part\".<br>La cas des handicapés nous renvoie ainsi à notre manière de penser le travail et le chômage, où nous considérons \"naturellement\" qu’il ya des travailleurs privés d’emploi et des travailleurs avec emploi, sans nous poser la question des frontières de cet ensemble, et en particulier de la manière dont ces frontières sont de plus en plus restreintes sous la pression d’une exclusion qui va de soit : ainsi, depuis longtemps déjà, dans les discours officiels et même politiques, les personnes au RMI ne sont-elles plus comptées dans l’emploi et le chômage.<br><a href=\"../AUTOparadisioboules/autodiag0-sauvegarde.htm?8\" target=\"_blank\">Voire à ce sujet la carte commentée sur l'évolution d l'AAH de 98 à 2005</a>"