<?php



$haut='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html><head><meta http-equiv="Content-type" content="text/html; charset=utf-8"><meta http-equiv="Content-Script-Type" content="text/javascript"><meta http-equiv="expires" content="0"><meta http-equiv="pragma" content="no-cache"><meta http-equiv="cache-control" content="no-cache, no-store, max-age=10, must-revalidate"> <script language="javascript" src="entete.js?updated=1234567890"></script> <script language="javascript" src="hypertexte.js"></script>  <script language="javascript">var tapX=parent.location.href;var topX=tapX.indexOf("MODIFaide");var tipX=tapX.indexOf("InterfaceDiscussion");var tepX=tapX.indexOf("Onglet");function OKici2(){if(topX>0){;parent.frames.changeaide.location.href="../ecrit_hypertext.html"}}</script><style type="text/css">a:link {  color:#0000E0; text-decoration:none ;} a:visited {  color:#0000A0; text-decoration:none ;} a:hover { font-weight:bold; color:#E00000; text-decoration:underline; } a:active { font-weight:bold; color:#E00000; text-decoration:underline ;} a:focus { font-weight:bold; color:#00E000; text-decoration:underline :} </style></head><body onload="if((topX>0 || tipX>0)& tepX<0){OKici2()}else{init()}" style="font-family:arial; font-size:10px;background-color:rgb(228, 228, 228)" onUnload="parent.rien()" >';

$haut2='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html><head><meta http-equiv="Content-type" content="text/html; charset=utf-8"><meta http-equiv="Content-Script-Type" content="text/javascript"><meta http-equiv="expires" content="0"><meta http-equiv="pragma" content="no-cache"><meta http-equiv="cache-control" content="no-cache, no-store, max-age=10, must-revalidate"> <script language="javascript" src="entete.js?updated=1234567890"></script> <script language="javascript" src="hypertexte.js"></script>  <script language="javascript">var tapX=parent.location.href;var topX=tapX.indexOf("MODIFaide");var tipX=tapX.indexOf("InterfaceDiscussion");var tepX=tapX.indexOf("Onglet");function OKici2(){if(topX>0){;parent.frames.changeaide.location.href="../ecrit_hypertext.html"}}</script><style type="text/css">a:link {  color:#0000E0; text-decoration:none ;} a:visited {  color:#0000A0; text-decoration:none ;} a:hover { font-weight:bold; color:#E00000; text-decoration:underline; } a:active { font-weight:bold; color:#E00000; text-decoration:underline ;} a:focus { font-weight:bold; color:#00E000; text-decoration:underline :} </style></head><body onload="if((topX>0 || tipX>0)& tepX<0){OKici2()}else{init()}" style="font-family:arial; font-size:10px;background-color:rgb(228, 228, 228)" onUnload="parent.rien()" >';


$bas='<a name="xbas"></a>
<script language="javascript" src="numeroationHyperTexte.js?updated=1234567890">var rien</script>
</body></html>';


?>